#!/usr/bin/env bash
# Run Taskologic for development as your own user, contained in this checkout.
# Everything it creates lives in dev/, which is gitignored. See docs/running-dev.md.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEV="$ROOT/dev"
DAEMON_CFG="$DEV/taskologicd.toml"
CLIENT_CFG="$DEV/client.toml"
DB="$DEV/taskologic.db"
LOG="$DEV/taskologicd.log"
PID="$DEV/taskologicd.pid"
# Unix socket paths are limited to about 100 bytes. A deep checkout goes to /tmp.
SOCK="$DEV/taskologicd.sock"
if [ "${#SOCK}" -gt 100 ]; then
  SOCK="/tmp/taskologicd-$(id -u).sock"
fi

usage() {
  cat <<USAGE
usage: scripts/dev.sh <command>

  up        build, start the daemon in the background, run the client,
            stop the daemon when the client exits
  daemon    build and run the daemon in the foreground (debug logging)
  client    build and run the client against the dev daemon
  stop      stop a background daemon
  socat     open a raw protocol session, type JSON lines (see docs/running.md)
  sql       open the dev database in sqlite3
  barcode   print a scannable payload: scripts/dev.sh barcode K4M9Q2 [S|F]
  reset     stop the daemon and delete the database, socket and log
  init      only write dev/taskologicd.toml and dev/client.toml

Environment: TASKOLOGICD_LOG (default debug) controls daemon logging.
USAGE
}

host_tz() {
  # /etc/localtime is a symlink into a zoneinfo tree on macOS and most Linux.
  local target
  target="$(readlink /etc/localtime 2>/dev/null || true)"
  case "$target" in
    *zoneinfo/*) echo "${target##*zoneinfo/}" ;;
    *) echo "UTC" ;;
  esac
}

init() {
  mkdir -p "$DEV"
  if [ ! -f "$DAEMON_CFG" ]; then
    cat > "$DAEMON_CFG" <<CFG
# Development daemon config, generated by scripts/dev.sh. Safe to edit.
socket_path = "$SOCK"
db_path = "$DB"
# Any group you belong to. A real install uses "taskologic".
group = "$(id -gn)"
always_admin_uids = []
print_job_max_age_secs = 14400
# Short tick so archiving, repeats and reminders are quick to watch.
scheduler_tick_secs = 5
host_timezone = "$(host_tz)"
CFG
    echo "wrote $DAEMON_CFG"
  fi
  if [ ! -f "$CLIENT_CFG" ]; then
    cat > "$CLIENT_CFG" <<CFG
# Development client config, generated by scripts/dev.sh. Safe to edit.
socket_path = "$SOCK"
print_priority = 0

# Uncomment to print through a CUPS queue (lpstat -p lists them). Without a
# printer section the client tells the daemon it cannot print and jobs wait
# in the queue until a client with a printer connects or they expire.
# [printer]
# queue = "receipt"
# paper = "mm58"
# codepage = "cp437"
# auto_cutter = true
# native_symbologies = ["code39", "code128"]
CFG
    echo "wrote $CLIENT_CFG"
  fi
}

build() {
  (cd "$ROOT" && cargo build --workspace)
}

daemon_running() {
  [ -f "$PID" ] && kill -0 "$(cat "$PID")" 2>/dev/null
}

start_daemon_bg() {
  if daemon_running; then
    echo "daemon already running (pid $(cat "$PID"))"
    return
  fi
  TASKOLOGICD_LOG="${TASKOLOGICD_LOG:-debug}" "$ROOT/target/debug/taskologicd" --config "$DAEMON_CFG" >"$LOG" 2>&1 &
  echo $! > "$PID"
  # Wait for the socket so the client does not race it.
  for _ in $(seq 1 50); do
    [ -S "$SOCK" ] && break
    sleep 0.1
  done
  if ! daemon_running; then
    echo "daemon failed to start, see $LOG:" >&2
    cat "$LOG" >&2
    rm -f "$PID"
    exit 1
  fi
  echo "daemon started (pid $(cat "$PID")), log: $LOG"
}

stop_daemon() {
  if daemon_running; then
    kill "$(cat "$PID")" 2>/dev/null || true
    for _ in $(seq 1 50); do
      daemon_running || break
      sleep 0.1
    done
  fi
  rm -f "$PID"
}

# If the client dies without restoring the terminal, leftover mouse
# reporting or a hidden cursor makes the shell look frozen. Cheap to always
# undo both after the client exits.
reset_terminal() {
  printf '\033[?1000l\033[?1002l\033[?1003l\033[?1006l\033[?1049l\033[?25h' 2>/dev/null || true
  stty sane 2>/dev/null || true
}

case "${1:-}" in
  init)
    init
    ;;
  daemon)
    init
    build
    exec env TASKOLOGICD_LOG="${TASKOLOGICD_LOG:-debug}" "$ROOT/target/debug/taskologicd" --config "$DAEMON_CFG"
    ;;
  client)
    init
    build
    TASKOLOGIC_CONFIG="$CLIENT_CFG" "$ROOT/target/debug/taskologic" || true
    reset_terminal
    ;;
  up)
    init
    build
    start_daemon_bg
    trap stop_daemon EXIT
    TASKOLOGIC_CONFIG="$CLIENT_CFG" "$ROOT/target/debug/taskologic" || true
    reset_terminal
    ;;
  stop)
    stop_daemon
    echo "daemon stopped"
    ;;
  socat)
    init
    exec socat - "UNIX-CONNECT:$SOCK"
    ;;
  sql)
    init
    exec sqlite3 "$DB"
    ;;
  barcode)
    shift
    (cd "$ROOT" && cargo run -q -p taskologic-core --example payload -- ${@+"$@"})
    ;;
  reset)
    stop_daemon
    rm -f "$DB" "$DB-wal" "$DB-shm" "$SOCK" "$LOG"
    echo "dev database, socket and log removed"
    ;;
  *)
    usage
    exit 2
    ;;
esac
